name: Build

on:
  workflow_call:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
        # Set work dir to "project" for all 'run' calls. Beware, everything else
        # (actions, 'with' params, etc.) still needs to reference full path.
        working-directory: project

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: project

      - name: Github REF
        run: echo $GITHUB_REF

      - name: Retrieve cache
        uses: actions/cache@v3
        env:
          cache-name: cache-modules
        with:
          path: |
            bootloader
            modules
            nrf
            nrfxlib
            test
            tools
            zephyr
            ~/.local/share/east/downloads/
            ~/.local/share/east/nrfutil-toolchain-manager.exe
          # Note above two lines, if we are caching entire ~/.local/share/east
          # folder then cache action fails during download/extract step
          key:
            ${{ runner.os }}-build-v2-${{ env.cache-name }}-${{
            hashFiles('project/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: "pip"
          cache-dependency-path: project/scripts/requirements.txt

      - name: Install East and West
        run: |
          pip install -r scripts/requirements.txt

      - name: Debug 1
        run: |
          pwd
          ls -al
          echo "Outside"
          ls -al ..

      - name: Initialize West manifest directory
        run: |
          west init -l .

      - name: Debug 2
        run: |
          pwd
          ls -al
          echo "Outside"
          ls -al ..

      - name: Update West manifest directory
        run: |
          west update -o=--depth=1 -n

      - name: Debug 3
        run: |
          pwd
          ls -al
          echo "Outside"
          ls -al ..

      - name: Install Toolchain manager
        run: |
          east sys-setup
          # Below line is needed, as the toolchain manager might be cached, but not configured
          ~/.local/share/east/nrfutil-toolchain-manager.exe config --install-dir ~/.local/share/east

      - name: Install NCS Toolchain
        run: |
          east update toolchain

      - name: Build firmware
        run: |
          east release

      - name: Archive firmware
        uses: actions/upload-artifact@v3
        with:
          name: release-files
          path: project/release
